### ISSUE TITLE
indicator to the agent once  a user answered

### ISSUE THREAD

**Issue by waleedsamy** [waleedsamy/CallCenterAgentApp#23]
_From @waleedsamy on August 12, 2015 10:19_
### Meta

[Asana task](https://app.asana.com/0/21349006331658/40672010877099) was created at Jul-08-2015 13:56 UTC.

_Copied from original issue: Ubicall/Nodejs-Call-Center#26_

**Comment by hagry** [comment]
https://github.com/Ubicall/CallCenterAgentApp/issues/31
Ubicall/CallCenterAgentApp#31

**Comment by waleedsamy** [comment]
Merged with #14
