### ISSUE TITLE
FreeSwitch flash settings

### ISSUE THREAD

**Issue by hagry** [waleedsamy/CallCenterAgentApp#39]
flash does not get appropriate settings approval when u click accept so no voice coming from agent

**Comment by waleedsamy** [comment]
**intro**
  The Flex compiler converts MXML mark-up into ActionScript-3 code before compiling it to SWF/SWC.

source of freeswitch swf is [freeswitch.mxml](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml) which expose it's functionality throw well defined function writen as actionScript in [mx:Script tag](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#6).

**sample of exposed functions:**
- [makeCall(number:String, account:String, evt:Object):void](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#48)
- [public function sendDTMF(digits:String, duration:int):void ](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#57)
- [public function answer(uuid:String):void](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#36)
- [public function hangup(uuid:String):void](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#76)
- [public function register(account:String, nickname:String):void](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#58)
- [public function unregister(account:String, nickname:String):void](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#48)
- [public function isMuted():Boolean](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#48) **which called to determine if privacy dialog will show or not.** 
- [public function showPrivacy():void](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#148) **will show the privacy dialog.**
- [public function setVolume(value:Number):void](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#164) **will set your phone sound volume.**
- [public function setMicVolume(value:Number):void](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.mxml#171) **will set your Microphone sound volume.**

**so how we show privacy dialog and permission modal for agent:**
- load flash as fsrtmp
- check with fsrtmp.isMuted
  - if true will show permission modal and show privacy dialog with fsrtmp.showPrivacy
  - if false mean you don't have to change anything

**Comment by waleedsamy** [comment]
@amegalla i am pretty sure that our implementation match with default [FreeSwitch sample implementation](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.html).

you can cheek [here](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.html#172) where he check if mic is mute and then show privacy dialog.

[privacy dialog](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.html#363) which is usual jquery popup and has content of flash and [show privacy flash function was called.](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/clients/flex/freeswitch.html#394)
